### ISSUE TITLE
知乎话题列表布局错误

### ISSUE THREAD

**Issue by garrydzeng** [Frizen/Plains-Gate#8]
如截图所示
<img width="516" alt="2016-05-14 23 37 52" src="https://cloud.githubusercontent.com/assets/1240290/15269298/fd2a435c-1a2c-11e6-9243-4d9e20321535.png">

页面是 https://www.zhihu.com/topic
环境是 OS X 10.11.4 Safari + Flat_Zhihu v2.3.1 beta2

**Comment by miyuchina** [comment]
遇到了同样的问题，OS X 10.11.4, Google Chrome, Flat_Zhihu v2.3.1 Beta 2.

检查发现是 153 行及 158-160 行之间的问题：

``` css
@media (max-width: 1400px) and (min-width: 968px) {
    /* ... */
    .feed-main {
        margin: -3px 0 2px 48px!important;
    }
    /* ... */
}
```

那个 `margin-left: 48px;` 应该改为 0px.

不过一旦改了以后官网就乱成一锅粥了……
